### ISSUE TITLE
got an unexpected error with no filetype specified

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#153]
I was uploading a file and I got the following error. Irina, any idea why the filetype is missing?

![upload-right and left](https://user-images.githubusercontent.com/41396793/106923616-44eaaa00-66dc-11eb-866b-c04abe6f3572.JPG)

**Comment by irina060981** [comment]
It is strange - I see that file input is empty, but if I click on upload with empty field it doesn't execute.
If I select a file and upload, an input won't be cleared.

What exact steps did you do?

**Comment by monzug** [comment]
I was uploading a tsv file in origin and a different one in target text. I could not reproduce this scenario, that's why I was asking when this error is generated. Thanks

**Comment by irina060981** [comment]
This error is generated when you upload file that has less then 2 rows.
Because it is expected to have the first row - with HEADER data , and other for the text

**Comment by monzug** [comment]
interesting. I am going to try this

**Comment by monzug** [comment]
I didn't get any error with a tsv file with one row.

**Comment by irina060981** [comment]
>I didn't get any error with a tsv file with one row.

I think I have already redefine this upload workflow in some change. 
The application supports two variants:
1. a file has more than 1 row and the first row has keyword HEADER - 
   than uploader gets properties (direction, language, sourceType) from the first row and other rows are defined as a text
2. a file has 1 row or the first row doesn't have HEADER keyword
    all file is defined as a text
    
So I think we doesn't have this error now

**Comment by monzug** [comment]
I did alignment with an empty TEI file and I did not get any error, not even in the log, so I think this has changed from Feb 5 (see comments above).
If possible I would like to have a list of errors so I can review them and also try to reproduce the scenario. Would that be possible? Thankf

**Comment by irina060981** [comment]
date-time format is updated to
DD-MM_HH24-MI

**Comment by irina060981** [comment]
>If possible I would like to have a list of errors so I can review them and also try to reproduce them. Would that be possible? Thanks

It is possible but need some time to collect all of them - would do this

**Comment by irina060981** [comment]
I prepared Errors and Info messages

ERROR
1. ALIGNED_CONTROLLER_NOT_READY_FOR_TOKENIZATION
"Document source texts are not ready for tokenization."
Shown when
  - not all parameters defined for the text (language, sourceType, direction, text)
  - all texts are already tokenized
Comments:
  Should not be ever shown, because Align button should not be available in these conditions.

2. ALIGNED_CONTROLLER_NOT_EQUAL_SEGMENTS
Shown when 
  - recieved results of the tokenization
  - number of segments is not equal for origin and targets texts

3. DOWNLOAD_CONTROLLER_ERROR_TYPE
Shown when
  - passed an unsupported download type
Comments:
  Should not be ever shown, because you could download only with the type defined in the select.

4. DOWNLOAD_CONTROLLER_ERROR_NO_TEXTS
Shown when
  - download single text and no text is defined
Comments:
  Should not be ever shown, because Download button should be disabled.

5. TEXTS_CONTROLLER_ERROR_WRONG_ALIGNMENT_STEP
"You should start from defining origin text first."
Shown when
  - a user defines target text before Alignment is initialized
  - a user deletes text before Alignment is initialized
Comments:
  Should not be ever shown, because Alignment is initialized on page load.

6. UPLOAD_CONTROLLER_EXTENSION_UNAVAILABLE
"File extension {extension} is not supported. Use the following - {availableExtensions}."
Shown when 
  - a user uploads file with unsupported extension (used both for main menu and for text single menu)

7.TEXTS_CONTROLLER_EMPTY_FILE_DATA
"The file doesn't have all the required fields. Text won't be created."
Shown when
  - upload data from an empty file (used both for main menu and for text single menu)

8. TOKENIZE_CONTROLLER_ERROR_NOT_REGISTERED
"Tokenizer method {tokenizer} is not registered"
Shown when
  - used an unsupported tokenize method
Comments:
  Should not be ever shown, because a tokenizer are chosen from a select.

9. TOKENS_EDIT_SPLIT_NO_SPACES
"The token word should have one space for split workflow."
Shown when
  - a user should click split for a token in Tokens Editor
  - clicked token's text doesn't have a space 

10. TOKENS_EDIT_SPLIT_SEVERAL_SPACES
"The token word should have only one space for split workflow."
Shown when
  - a user should click split for a token in Tokens Editor
  - clicked token's text has more then 1 space 

11. TOKENS_EDIT_IS_NOT_EDITABLE_ERROR
"This token is inside created alignment group, you should ungroup it first."
Shown when 
  - a user did any token's edit action on a token
  - this token is already grouped
Comments:
  Should not be ever shown, because grouped tokens doesn't have edit menu.

12. UPLOAD_CONTROLLER_ERROR_TYPE
"Upload type {uploadType} is not defined."
Shown when
  - passed an unsupported upload type
Comments:
  Should not be ever shown, because an application selects upload type based on file extension. Unsupported extensions won't reach this stage.

13. UPLOAD_CONTROLLER_ERROR_WRONG_FORMAT
"Uploaded file has wrong format for the type - plainSourceUploadFromFile."
Shown when
Main menu:
  - a user uploads file with tsv/csv extension 
  - a file has less then 2 rows (this way no texts are defined, because text parameters - language, direction, sourceType are defined in the first (HEADER) row)
Single text menu  
  - a user uploads file with tsv/csv extension 
  - the first row has HEADER keyword (language, direction, sourceType are defined in such a row)
  - there is only one row in the file (this way there is no text in a file )

14. ALIGNMENT_ERROR_ADD_TARGET_SOURCE
"First you should define origin source text."
Shown when
  - a user defines a target text before origin text is defined

15. ALIGNMENT_ERROR_TOKENIZATION_CANCELLED
"Tokenization was cancelled."
Shown after ALIGNED_CONTROLLER_NOT_READY_FOR_TOKENIZATION

16. ALIGNMENT_ORIGIN_NOT_TOKENIZED
"Origin source text was not tokenized due to the errors in tokenization service. All tokenization results were cancelled."
Shown when
  - tokenization was started
  - origin text was not tokenized and error was recieved (for example defined plain text, sourceType is selected as TEI)

17. ALIGNMENT_TARGET_NOT_TOKENIZED
"Target source text № {textnum} was not tokenized due to the errors in tokenization service. All tokenization results were cancelled."
Shown when
  - tokenization was started
  - target text was not tokenized and error was recieved (for example defined plain text, sourceType is selected as TEI)

18. ALIGNMENT_ERROR_ADD_TO_ALIGNMENT
"Choose another token please - from the same segment, target text."
Shown when
  - a user tries to add an incorrect token to the group (from another segment, from another targetId)

19. ALIGNMENT_ERROR_REMOVE_FROM_ALIGNMENT
"Alignment doesn't have such tokens."
Shown when 
  - a user tries to remove an incorrect token (for example not grouped token)
Comments:
  Should not be ever shown, because there is no action for removing an ungrouped token.

20. ALIGNMENT_ERROR_ACTIVATE_BY_INDEX
"Passed index is out of the group list bounds - {index}"
Shown when
  - a user activates non-existant group 
Comments:
  Should not be ever shown, because there is no action for such an activating.

21. TOKENS_EDIT_IS_NOT_EDITABLE_MERGETO_TOOLTIP
"The token that is the target of merging is inside a created alignment group, you should ungroup it first."
Shown when
  - a user tries merge a token with already grouped token

22. SOURCE_TEXT_CONVERT_ERROR
"The file doesn't have all the required fields. Text won't be created."
Shown when 
  - a user uploads json file 
  - text filed is not defined a json file

23. TOKENS_EDIT_UNDO_ERROR
"Nothing to undo."
Shown when 
  - a user tries to undo an action when there were no done steps
Comments:
  Should not be ever shown, because the undo button should be disabled in this case.

24. TOKENS_EDIT_REDO_ERROR
"Nothing to redo."
Shown when 
  - a user tries to redo an action when there were no undone steps
Comments:
  Should not be ever shown, because the redo button should be disabled in this case.

INFO
1. ALIGNED_CONTROLLER_TOKENIZATION_STARTED
"Tokenization process has started."
Shown when
  - all checks for ready to tokenizaion are done 
  - tokenization is started

2. ALIGNED_CONTROLLER_TOKENIZATION_FINISHED
"Tokenization process has finished."
Shown when 
  - the tokenization result is recieved from the tokenizer
  - results are converted to tokens or an error is recieved

**Comment by irina060981** [comment]
@monzug , there are several errors that should not be shown ever. 
But they are defined because application would be debeloped further and some actions could become available in future.
I think that you should skip such Errors, but I decided to list them here for future cases.

**Comment by monzug** [comment]
Fantastic. Thanks so much Irina. I might need your help to reproduce some
messages. great.

**Comment by monzug** [comment]
Actually I was able to generate the error originally reported in this issue: Uploaded file has wrong format for the type - plainSourceUploadFromFile.
For some obscure reason I was able to download a json and Origin tsv and Target tsv with empty text. On upload of tsv, I got the above error. see screenshot

![Screen Shot 2021-03-18 at 2 57 47 PM](https://user-images.githubusercontent.com/41396793/111638407-949fb380-87fa-11eb-9031-8ea0b68061e9.png)

this is the empty tsv: 
[18-03_14-33-alignment-eng.tsv.zip](https://github.com/alpheios-project/alignment-editor-new/files/6164666/18-03_14-33-alignment-eng.tsv.zip)

**Comment by irina060981** [comment]
I found the conditions when you could create such an empty file, there were several bugs:
- there was no opportunity to delete text (if you delete it from the textArea and download - it would still have previous text)
- download button could be available when text is empty (because of previous)

I fixed both

**Comment by monzug** [comment]
yes, now I am not longer able to download an empty file. Thanks!

**Comment by monzug** [comment]
2) ALIGNED_CONTROLLER_NOT_EQUAL_SEGMENTS is probably the following error message: The tokenization process was cancelled because origin and target texts don't have the same amount of segments.

**Comment by monzug** [comment]
7. TEXTS_CONTROLLER_EMPTY_FILE_DATA
"The file doesn't have all the required fields. Text won't be created."
Shown when

upload data from an empty file (used both for main menu and for text single menu)

Actually, when uploading an empty file, I am getting: Uploaded file has wrong format for the type - plainSourceUploadFromFile. @irina060981, Am I getting this right?

**Comment by monzug** [comment]
> I found the conditions when you could create such an empty file, there were several bugs:
> 
> * there was no opportunity to delete text (if you delete it from the textArea and download - it would still have previous text)
> * download button could be available when text is empty (because of previous)
> 
> I fixed both

@irina060981  Irina, the download button is still available with empty text. accordingly to your comment above, this should no longer be the case. at fresh start of alignment editor, the download button is highlighted and it shouldn't. see screenshot

![Screen Shot 2021-03-23 at 4 20 46 PM](https://user-images.githubusercontent.com/41396793/112171684-5805fa80-8bf4-11eb-9377-ffee8baf905d.png)

**Comment by monzug** [comment]
message 13. confirmed that message is generated when uploading an empty tsv. see screenshot
![Screen Shot 2021-03-24 at 3 29 43 PM](https://user-images.githubusercontent.com/41396793/112327744-fd34d780-8cb5-11eb-9c42-740b7514d5bb.png)

**Comment by monzug** [comment]
tested the messages that I was able to reproduce. my comments above. 
Alpheios Translation Alignment editor 1.3.1 (build development.20210319 83)

**Comment by irina060981** [comment]
>ALIGNED_CONTROLLER_NOT_EQUAL_SEGMENTS is probably the following error message: The tokenization process was cancelled because origin and target texts don't have the same amount of segments.

Oh, I missed it in the list - added to the post

**Comment by irina060981** [comment]
>upload data from an empty file (used both for main menu and for text single menu)

>Actually, when uploading an empty file, I am getting: Uploaded file has wrong format for the type - plainSourceUploadFromFile. @irina060981, Am I getting this right?

@monzug, I tried empty .tsv, .txt and .json - all of them gave me the same error
![image](https://user-images.githubusercontent.com/12377640/112823323-796f5680-90cc-11eb-9be3-1e3d405fede9.png)

If you could reproduce it - give me a file that you uploaded and steps, please

**Comment by irina060981** [comment]
>for this error message, I have two errors:
The token word should have only one space for split workflow. and also,
The token word should have one space for split workflow.
I understand that there are two different scenarios for these errors but the two error messages are the same except for 'only'.

Monica, may be you have suggestion for more correct messages?

**Comment by irina060981** [comment]
>@irina060981 Irina, the download button is still available with empty text. accordingly to your comment above, this should no longer be the case. at fresh start of alignment editor, the download button is highlighted and it shouldn't. see screenshot

Thank you for the catch - fixed

**Comment by irina060981** [comment]
>message 13. confirmed that message is generated when uploading an empty tsv. see screenshot

I have only one correct message is reproduced.
I need more detailed steps to reproduce it

**Comment by monzug** [comment]
> > upload data from an empty file (used both for main menu and for text single menu)
> 
> > Actually, when uploading an empty file, I am getting: Uploaded file has wrong format for the type - plainSourceUploadFromFile. @irina060981, Am I getting this right?
> 
> @monzug, I tried empty .tsv, .txt and .json - all of them gave me the same error
> ![image](https://user-images.githubusercontent.com/12377640/112823323-796f5680-90cc-11eb-9be3-1e3d405fede9.png)
> 
> If you could reproduce it - give me a file that you uploaded and steps, please

see attached the empty file and the screenshot of the errors in the log
[18-03_14-33-alignment-eng.tsv.zip](https://github.com/alpheios-project/alignment-editor-new/files/6222069/18-03_14-33-alignment-eng.tsv.zip)

![Screen Shot 2021-03-29 at 3 38 22 PM](https://user-images.githubusercontent.com/41396793/112845314-056d8800-90a5-11eb-9891-7f4250acb26b.png)

**Comment by monzug** [comment]
> > @irina060981 Irina, the download button is still available with empty text. accordingly to your comment above, this should no longer be the case. at fresh start of alignment editor, the download button is highlighted and it shouldn't. see screenshot
> 
> Thank you for the catch - fixed

yes, this is fixed. Thanks

**Comment by irina060981** [comment]
>see attached the empty file and the screenshot of the errors in the log
steps to repro: just click on upload from top menu and select this file or from upload from target text. Note that my empty tsv file was creating by downloading an empty file from alignment editor (before the recently fix).

Thank you for the details - I found the source of the error and fixed.

**Comment by irina060981** [comment]
@monzug , may be you missed my question

for this error message, I have two errors:
The token word should have only one space for split workflow. and also,
The token word should have one space for split workflow.
I understand that there are two different scenarios for these errors but the two error messages are the same except for 'only'.

Monica, may be you have suggestion for more correct messages?

see below few suggestions

Only one space is allowed for split workflow. or
The token word cannot contain more than one space for split workflow.
and
The token word must contain at least one space for split workflow.

**Comment by monzug** [comment]
> > see attached the empty file and the screenshot of the errors in the log
> > steps to repro: just click on upload from top menu and select this file or from upload from target text. Note that my empty tsv file was creating by downloading an empty file from alignment editor (before the recently fix).
> 
> Thank you for the details - I found the source of the error and fixed.

Thanks. Now I am getting the following message: The file doesn't have all required fields. Text won't be created.
Alpheios Translation Alignment editor 1.3.1 (build development.20210330238)

**Comment by monzug** [comment]
> @monzug , may be you missed my question
> 
> for this error message, I have two errors:
> The token word should have only one space for split workflow. and also,
> The token word should have one space for split workflow.
> I understand that there are two different scenarios for these errors but the two error messages are the same except for 'only'.
> 
> Monica, may be you have suggestion for more correct messages?
> 
> see below few suggestions
> 
> Only one space is allowed for split workflow. or
> The token word cannot contain more than one space for split workflow.
> and
> The token word must contain at least one space for split workflow.

Irina, these are my suggestions:

1) for 'The token word should have one space for split workflow.' I would go with 'The token word must contain at least one space for split workflow.'

2) for 'The token word should have only one space for split workflow.' I would update as follow 'The token word cannot contain more than one space for split workflow.' or 'Only one space is allowed for split workflow.'

**Comment by monzug** [comment]
Messages have been updated, tested in Alpheios Translation Alignment editor 1.3.1 (build development.20210331335)
