### ISSUE TITLE
Delete still available in Original Text after alignment

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#345]
tested in Alpheios Translation Alignment editor 1.3.3 (build development.20210426.95) 

Enter Original and 3 translation texts, then do an alignment. go to Source text editor.
Only Original text has the garbage bin icon available, while all the other 3 translation do not. When I click on it, it clears text but I cannot edit the box or upload a new file. Bottom line, garbage bin should not be in the Original text after alignment.

garbage bin available in Source text editor after alignment
![Screen Shot 2021-04-26 at 2 17 40 PM](https://user-images.githubusercontent.com/41396793/116083529-f88c8600-a69c-11eb-8686-7e5d966e03ff.png)

after clear text
![Screen Shot 2021-04-26 at 2 40 04 PM](https://user-images.githubusercontent.com/41396793/116083830-6173fe00-a69d-11eb-904b-c7886780ba5c.png)

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
I still see the Garbage bin in source text editor after alignment in Alpheios Translation Alignment editor 1.3.3 (build development.20210429332)

**Comment by irina060981** [comment]
I found reproducable steps - and fixed.
No I was not able again reproduce it.

**Comment by monzug** [comment]
Fixed. Thanks
