### ISSUE TITLE
with indexedDB turned off, I cannot navigate to the next section

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#518]
related to #503 and  #460  and  #511

tested in Chrome/PC in build dated 2/9

I turned off indexedDB support, and resume an alignment with less than 5000 chars. I wanted to test the effect of editing on the display of the text in align text. First I noticed that the tiles were still visible for a text with less than 5000 chars, second I got the following error when clicking on the second next which prevented me from going to the next section.
Note that the same issue is reproducible when I  start a new alignment.

I did also upload the same text with indexedDB turned on. I could navigate to the end of the text without errors.

see screenshot below

![navigation-error](https://user-images.githubusercontent.com/41396793/132221239-ece4c8bb-6cfd-4f4f-a137-5c89ea79f6b3.JPG)

this is also reproducible in production.

When I increased the Max chars per part to 5000 (the max allowed) then I did not have any problem as the text was displayed with no tiles and in one page (see #511).

**Comment by irina060981** [comment]
Oh, I forgot to turn off parts division support if IndexedDB is turned off.
Thank you for the catch!

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
question: if indexedDB is turned off, should I still see parts (as I do in  Christoph's text in chinese and english) ?

**Comment by monzug** [comment]
see screenshots related to question 1

![tiles-indexeddboff](https://user-images.githubusercontent.com/41396793/132532425-f36d2955-bd39-49c4-83f0-98fec55db1ce.JPG)
![indexeddboff](https://user-images.githubusercontent.com/41396793/132532439-993f0c4b-8c6a-4d7c-af80-0b52016887de.JPG)

**Comment by irina060981** [comment]
>question 1: if indexedDB is turned off, should I still see parts (as I do in Christoph's text in chinese and english) ? I am very confused by what I have been testing.

Yes you see parts, but they didn't saved to the IndexedDB, they are stored to memory.
And if you have enough memory on the computer or text is not too long - you won't see any difference.

I decided no to decrease dunctionality as possible.

So you should simply check - that when IndexedDB support is turned off - a user could navigate through parts.

**Comment by irina060981** [comment]
>question 2: can we remove from the build the max chars per part? it is not going into Pietro's build and I am afraid this can cause some problems, do you?

It was a requirement from Harry on the last week.
And I use it - it doesn't cause problems for me. So I would prefer not to remove it if to be honest.

**Comment by monzug** [comment]
tested in FF/PC. with indexedDB turned off I can navigate to the next part with no errors.
