### ISSUE TITLE
Mixed texts saved in HTML output and json file

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#530]
related to issue #520 and #523
with indexedDB on or off,  saved texts (after editing) with parts in HTML output (or json file) has corrupted texts. the lines get mixed in awkward ways such repetition or misplaced

see screenshot of html output
![mixed-texts](https://user-images.githubusercontent.com/41396793/132694792-ab8b275f-b41c-431c-a66d-f5da0a9a115f.JPG)

see original json file before editing
[09-09_09-15-full-alignment-lat-eng.zip](https://github.com/alpheios-project/alignment-editor-new/files/7136913/09-09_09-15-full-alignment-lat-eng.zip)

see screenshot of json after editing and saved as json (note that indexedDB file displays correctly)
![json-with-mixed-text](https://user-images.githubusercontent.com/41396793/132709927-b8a13f21-dccc-4780-9d6e-ecb2bef20537.JPG)

**Comment by monzug** [comment]
tested in Chrome/Mac and FF/PC

**Comment by monzug** [comment]
I did also testing with segments. with indexedDB off, both HTML output and json file looked good. with indexedDB on,  the same text with no segments (I removed the blank lines), json file and HTML output have corrupted texts. The same text with segments has an indexedDB file with misplaced segments but both the HTML output and json file looked good.

![repetition](https://user-images.githubusercontent.com/41396793/132875388-9097ab15-a7e4-4b59-a247-c23db752a1fa.JPG)

**Comment by irina060981** [comment]
I fixed the problem with tokens sorting
Hope it is all with this problem

**Comment by monzug** [comment]
I still see problems on html output and json file. as I quickly tested only on a greek file, I need more time to test this issue.

**Comment by irina060981** [comment]
I tried to reproduce - but I could not.
Pay attention that you should test from scratch - define texts firs, tokenize and then edit, do not use previously saved texts (they could be already mixed).

**Comment by monzug** [comment]
Yes I am careful at that. What I do is to insert words in editing and look for them in the output (html, json and indexedDB). In this case the words in original and translation texts were mixed up in output. As I said I need to do more testing as I only run a quick one in one browser with one text.

**Comment by irina060981** [comment]
oh, I forgot to check insert tokens

**Comment by irina060981** [comment]
@monzug , I found reproducable conditions - working to fix it

**Comment by irina060981** [comment]
This bug fixed - and again I hope - that's all for this bug :)

**Comment by monzug** [comment]
tested with indexedDB on and off, with multiple segments and not. looks good in FF/PC and Safari/Mac
