### ISSUE TITLE
Standard theme: can't see aligned tokens in all views except for 3 columns in HTML output

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#549]
in Standard theme, the HTML output has all black tokens in Full view so the aligned tokens are not visible. this is also true for Short, Equivalence and Sentence view, except for 3 columns view.
see screenshot
Full view
![no-highlight](https://user-images.githubusercontent.com/41396793/134922759-dd21c50d-df61-465e-8637-5ba2d4c8cfe5.JPG)

3 columns view
![3columns](https://user-images.githubusercontent.com/41396793/134922823-87e14d5a-1e95-449c-bbcf-6d2bbcd2043b.JPG)

**Comment by irina060981** [comment]
Fixed
![image](https://user-images.githubusercontent.com/12377640/135018141-378cc846-71af-45b1-bc54-d0cd10a1a682.png)

**Comment by monzug** [comment]
Irina, this is not fixed. The problem is that all tokens are black so you cannot see which one are aligned unless when you mouse over. On the contrary the 3 columns view has red tokens so the aligned tokens in black are visible.

**Comment by monzug** [comment]
Actually, in Safari it does not work. this can wait.

![Screen Shot 2021-09-28 at 7 36 00 AM](https://user-images.githubusercontent.com/41396793/135029337-0cec78d0-4dad-42a2-aa6e-1f5cd98ffa76.png)

**Comment by irina060981** [comment]
It is fixed for me in Safari
<img width="1437" alt="Screenshot 2021-09-28 at 19 37 40" src="https://user-images.githubusercontent.com/12377640/135062954-ab747bd4-5642-445d-98cf-3865b42c7407.png">

May be there is some cache in your case?

**Comment by monzug** [comment]
yes! you are right. it's highlighted now. Thanks for suggesting to clear the cache.
