### ISSUE TITLE
Upgrade checkXML method for TEI.2 tag

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#622]
We have DetectTextController.checkXML with a regexp that check if a text has TEI tag.
It is failed on 

```
<TEI.2>
<text>
this is body text
</text>
</TEI.2>
```

**Comment by irina060981** [comment]
Fixed

**Comment by monzug** [comment]
There is no way for me to test that we support TEI.2 now, correct? I am still getting empty content when I select TEI and not text.  If I select text, all tags are printed with the content.

**Comment by irina060981** [comment]
@monzug , I believe that I didn't fully explained the issue

It is only about the first step (I described in my letter)
I updated the method  that is responsible for text/tei icon only, not for tokenizer.

So now all inserted (not uploaded from the file - it is still detected by file extension) texts are checked - if they have <tei or < tei (case insensetive) - and if true, than we decide that it is tei - print this icon

That's all

Tokenization service upgrade would be done in https://github.com/alpheios-project/tokenizer/issues/29

**Comment by monzug** [comment]
If I copy content with TEI tag, I still have to change manually the Text icon into TEI icon. see screenshot below.

![Screen Shot 2022-01-18 at 3 15 30 PM](https://user-images.githubusercontent.com/41396793/149954039-dfc3f2e4-9055-4eec-ad49-40918a8cc802.png)

**Comment by irina060981** [comment]
@monzug, it checks at first text insert - and in my tests it works correctly.

But if you change the existed text - it doesn't add a new check and change the icon.
The icon is defined once (automatically) - and after that it could be changed only manualy.

If you have reproducable steps - please share with me

**Comment by irina060981** [comment]
ok, with the help of the attached file - I found the error in checking XML regexp
Now it is fixed
[t2fromperseus.zip](https://github.com/alpheios-project/alignment-editor-new/files/7894134/t2fromperseus.zip)
s

**Comment by monzug** [comment]
ok, now it's working: when copying TEI text into the alignment editor, icon is correctly set to TEI. see below

![Screen Shot 2022-01-19 at 3 59 54 PM](https://user-images.githubusercontent.com/41396793/150156751-bc9d92cf-d7a2-45d3-b128-c6cfdf23f8c7.png)
